# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antag
  id: Changeling
  name: roles-antag-changeling-name
  antagonist: true
  setPreference: true
  category: Solo
  icon:
    sprite: Objects/Weapons/Melee/armblade.rsi
    state: icon
  objective: roles-antag-changeling-description
  requirements:
  - !type:OverallPlaytimeRequirement
      time: 10h #10 hrs
  - !type:SpeciesRequirement
    inverted: true
    species:
    - IPC
    - Plasmaman
  guides: [ Changelings ]
