using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Erida.DirectionalEmote.UserInterface;

[GenerateTypedNameReferences]
public sealed partial class DirectionalEmoteWindow : FancyWindow
{
    public NetEntity Source;
    public NetEntity Target;
    public string Text = string.Empty;

    public bool HideName;

    public Action? AcceptPressed;
    public DirectionalEmoteWindow()
    {
        RobustXamlLoader.Load(this);


        AcceptButton.OnPressed += _ =>
        {
            AcceptPressed?.Invoke();
        };

        MessageInput.OnTextChanged += e =>
        {
            Text = Rope.Collapse(e.TextRope).Trim();
        };

        HideNameCheckBox.OnToggled += e =>
        {
            HideName = e.Pressed;
        };
    }

    public void SetText(string text)
    {
        Text = text;
        MessageInput.TextRope = new Rope.Leaf(text);
    }

    public void UpdateHideNameVisibility(bool visible)
    {
        HideNameCheckBox.Visible = visible;

        HideNameCheckBox.Pressed = false;
        HideName = false;
    }
}
