"Sprites":
- changed-files:
  - any-glob-to-any-file: '**/*.rsi/*.png'

"Map":
- changed-files:
  - any-glob-to-any-file:
    - 'Resources/Maps/**/*.yml'
    - 'Resources/Prototypes/Maps/**/*.yml'

"Prototypes":
- changed-files:
  - any-glob-to-any-file:
      - 'Resources/Prototypes/**/*.yml'
      - '!Resources/Prototypes/Maps/**/*.yml'

"UI":
- changed-files:
  - any-glob-to-any-file: '**/*.xaml*'

"Shaders":
- changed-files:
  - any-glob-to-any-file: '**/*.swsl'

"Audio":
- changed-files:
  - any-glob-to-any-file: '**/*.ogg'

"С#":
- changed-files:
  - any-glob-to-any-file: "**/*.cs"

