# SPDX-License-Identifier: AGPL-3.0-or-later
# erida edit - пул голосования: Основные карты (Backmen + Erida)

- type: gameMapPool
  id: DefaultMapPool
  maps:
  # - BackmenAspid
  # - BackmenBox
  # - BackmenHive
  # - BackmenKettle
  # - BackmenRook
  # - BackmenShoukou
  # - BackmenTortuga
  - EridaBox
  - EridaDelta
  - EridaAmber
  - EridaAspid
  - EridaBagel
  - EridaConvex
  - EridaElkridge
  - EridaFland
  - EridaHive
  - EridaKettle
  - EridaLoop
  - EridaMarathon
  - EridaMeta
  - EridaOasis
  - EridaOmega
  - EridaPlasma
  - EridaRook
  - EridaShoukou
  - EridaTortuga
  - EridaTrain