# SPDX-License-Identifier: AGPL-3.0-or-later
# erida edit - пул голосования: карты Эриды

- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Amber_Erida
  - BackmenAspid
  - BackmenBox
  - BackmenDelta
  - BackmenHive
  - BackmenKettle
  - BackmenRook
  - BackmenShoukou
  - BackmenTortuga
  - Bagel_Erida
  - Convex_Erida
  - Elkridge_Erida
  - Fland_Erida
  - Loop_Erida
  - Marathon_Erida
  - Meta_Erida
  - Oasis_Erida
  - Omega_Erida
  - Packed_Erida
  - Plasma_Erida
  - CorvaxSilly
  - Train
