// SPDX-License-Identifier: MIT

using System.Linq;
using System.Numerics;
using Content.Client.Guidebook.Controls;
using Content.Client.UserInterface.ControlExtensions;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Humanoid;

// erida edit - erida-style picker: searchable item grid with per-item preview, color picker and reorder
[GenerateTypedNameReferences]
public sealed partial class MarkingPicker : Control
{
    [Dependency] private readonly MarkingManager _markingManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly SpriteSystem _sprite;

    public Action<MarkingSet>? OnMarkingAdded;
    public Action<MarkingSet>? OnMarkingRemoved;
    public Action<MarkingSet>? OnMarkingColorChange;
    public Action<MarkingSet>? OnMarkingRankChange;

    private MarkingSet _currentMarkings = new();

    private List<MarkingCategories> _markingCategories = Enum.GetValues<MarkingCategories>().ToList();

    private string _currentSpecies = SharedHumanoidAppearanceSystem.DefaultSpecies;
    private Sex _currentSex = Sex.Unsexed;
    public Color CurrentSkinColor = Color.White;
    public Color CurrentEyeColor = Color.Black;
    public Marking? HairMarking;
    public Marking? FacialHairMarking;

    private readonly HashSet<MarkingCategories> _ignoreCategories = new();

    private readonly List<CategoryTab> _categoryTabs = new();

    public string IgnoreCategories
    {
        get => string.Join(',', _ignoreCategories);
        set
        {
            _ignoreCategories.Clear();
            var split = value.Split(',');
            foreach (var category in split)
            {
                if (!Enum.TryParse(category, out MarkingCategories categoryParse))
                {
                    continue;
                }

                _ignoreCategories.Add(categoryParse);
            }
        }
    }

    public bool Forced { get; set; }

    private bool _ignoreSpecies;

    public bool IgnoreSpecies
    {
        get => _ignoreSpecies;
        set => _ignoreSpecies = value;
    }

    public void SetData(List<Marking> newMarkings, string species, Sex sex, Color skinColor, Color eyeColor)
    {
        var pointsProto = _prototypeManager
            .Index<SpeciesPrototype>(species).MarkingPoints;
        _currentMarkings = new(newMarkings, pointsProto, _markingManager);

        SetData(_currentMarkings, species, sex, skinColor, eyeColor);
    }

    public void SetData(MarkingSet set, string species, Sex sex, Color skinColor, Color eyeColor)
    {
        _currentMarkings = new(set);

        if (!IgnoreSpecies)
        {
            _currentMarkings.EnsureSpecies(species, skinColor, _markingManager); // should be validated server-side but it can't hurt
        }

        _currentSpecies = species;
        _currentSex = sex;
        CurrentSkinColor = skinColor;
        CurrentEyeColor = eyeColor;

        Populate("");
    }

    public void SetSkinColor(Color color) => CurrentSkinColor = color;
    public void SetEyeColor(Color color) => CurrentEyeColor = color;

    public void SetSex(Sex sex)
    {
        _currentSex = sex;
        Populate("");
    }

    public void SetSpecies(string species)
    {
        _currentSpecies = species;
        Populate("");
    }

    public MarkingPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entityManager.System<SpriteSystem>();
    }

    private string GetMarkingName(MarkingPrototype marking) => Loc.GetString($"marking-{marking.ID}");

    private IReadOnlyDictionary<string, MarkingPrototype> GetMarkings(MarkingCategories category)
    {
        return IgnoreSpecies
            ? _markingManager.MarkingsByCategoryAndSex(category, _currentSex)
            : _markingManager.MarkingsByCategoryAndSpeciesAndSex(category, _currentSpecies, _currentSex);
    }

    public void Populate(string filter)
    {
        CMarkingTabs.RemoveAllChildren();
        _categoryTabs.Clear();

        var i = 0;
        foreach (var category in _markingCategories)
        {
            var markings = GetMarkings(category);
            if (_ignoreCategories.Contains(category) ||
                markings.Count == 0)
            {
                continue;
            }

            var tab = new CategoryTab(category, markings, this);
            _categoryTabs.Add(tab);
            CMarkingTabs.AddChild(tab);
            CMarkingTabs.SetTabTitle(i, Loc.GetString($"markings-category-{category.ToString()}"));
            i++;
        }
    }

    public void PopulateUsed()
    {
    }

    private void UpdatePoints()
    {
        foreach (var tab in _categoryTabs)
        {
            tab.UpdatePointsLabel();
        }
    }

    private void MarkingColorChange(List<Color> colors, MarkingCategories category, MarkingPrototype prototype)
    {
        var markingIndex = _currentMarkings.FindIndexOf(category, prototype.ID);
        if (markingIndex < 0)
            return;

        var marking = new Marking(_currentMarkings.Markings[category][markingIndex]);
        for (var i = 0; i < colors.Count && i < marking.MarkingColors.Count; i++)
        {
            marking.SetColor(i, colors[i]);
        }

        _currentMarkings.Replace(category, markingIndex, marking);
        OnMarkingColorChange?.Invoke(_currentMarkings);

        foreach (var tab in _categoryTabs)
        {
            tab.RefreshItems();
        }
    }

    private bool TrySelectMarking(MarkingPrototype prototype, MarkingCategories category)
    {
        if (_currentMarkings.PointsLeft(category) == 0 && !Forced)
        {
            return false;
        }

        var markingObject = prototype.AsMarking();

        // We need add hair markings in cloned set manually because _currentMarkings doesn't have it
        var markingSet = new MarkingSet(_currentMarkings);
        if (HairMarking != null)
        {
            markingSet.AddBack(MarkingCategories.Hair, HairMarking);
        }
        if (FacialHairMarking != null)
        {
            markingSet.AddBack(MarkingCategories.FacialHair, FacialHairMarking);
        }

        if (!_markingManager.MustMatchSkin(_currentSpecies, prototype.BodyPart, out var _, _prototypeManager))
        {
            // Do default coloring
            var colors = MarkingColoring.GetMarkingLayerColors(
                prototype,
                CurrentSkinColor,
                CurrentEyeColor,
                markingSet
            );
            for (var i = 0; i < colors.Count; i++)
            {
                markingObject.SetColor(i, colors[i]);
            }
        }
        else
        {
            // Color everything in skin color
            for (var i = 0; i < prototype.Sprites.Count; i++)
            {
                markingObject.SetColor(i, CurrentSkinColor);
            }
        }

        markingObject.Forced = Forced;

        _currentMarkings.AddBack(category, markingObject);
        OnMarkingAdded?.Invoke(_currentMarkings);
        UpdatePoints();
        return true;
    }

    private void TryDeselectMarking(MarkingPrototype prototype, MarkingCategories category)
    {
        if (!_currentMarkings.Remove(category, prototype.ID))
            return;

        OnMarkingRemoved?.Invoke(_currentMarkings);
        UpdatePoints();
    }

    private void ShiftMarking(MarkingPrototype prototype, MarkingCategories category, bool up)
    {
        var idx = _currentMarkings.FindIndexOf(category, prototype.ID);
        if (idx < 0)
            return;

        if (up)
            _currentMarkings.ShiftRankUpFromEnd(category, _currentMarkings.Markings[category].Count - idx - 1);
        else
            _currentMarkings.ShiftRankDownFromEnd(category, _currentMarkings.Markings[category].Count - idx - 1);

        OnMarkingRankChange?.Invoke(_currentMarkings);
    }

    private sealed class CategoryTab : BoxContainer
    {
        private readonly MarkingCategories _category;
        private readonly IReadOnlyDictionary<string, MarkingPrototype> _markings;
        private readonly MarkingPicker _picker;

        private readonly LineEdit _searchBar;
        private readonly ScrollContainer _selectionItems;
        private readonly GridContainer _items;
        private readonly ScrollContainer _orderingItems;
        private readonly BoxContainer _orderingList;
        private readonly Label _statusLabel;
        private readonly Button _reorderButton;
        private List<MarkingItem> _searchable = new();
        private const int _columnWidth = 500;

        public CategoryTab(MarkingCategories category, IReadOnlyDictionary<string, MarkingPrototype> markings, MarkingPicker picker)
        {
            _category = category;
            _markings = markings;
            _picker = picker;

            Orientation = LayoutOrientation.Vertical;
            HorizontalExpand = true;
            VerticalExpand = true;

            _searchBar = new LineEdit
            {
                PlaceHolder = Loc.GetString("markings-search"),
                HorizontalExpand = true,
            };
            _searchBar.OnTextChanged += _ =>
            {
                foreach (var element in _searchable)
                {
                    element.SetHiddenState(true, _searchBar.Text.Trim());
                }
            };
            AddChild(_searchBar);

            _items = new GridContainer
            {
                Columns = 1,
                Margin = new Thickness(4),
            };
            _selectionItems = new ScrollContainer
            {
                HorizontalExpand = true,
                VerticalExpand = true,
            };
            _selectionItems.AddChild(_items);
            AddChild(_selectionItems);

            foreach (var marking in _markings.Values.OrderBy(marking => Loc.GetString($"marking-{marking.ID}")))
            {
                _items.AddChild(new MarkingItem(marking, this));
            }
            _searchable = _items.GetSearchableControls().Cast<MarkingItem>().ToList();

            _orderingList = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };
            _orderingItems = new ScrollContainer
            {
                HorizontalExpand = true,
                VerticalExpand = true,
                Visible = false,
            };
            _orderingItems.AddChild(_orderingList);
            AddChild(_orderingItems);

            var bottom = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(4),
                SeparationOverride = 4,
            };
            _statusLabel = new Label { HorizontalExpand = true };
            bottom.AddChild(_statusLabel);
            _reorderButton = new Button
            {
                Text = Loc.GetString("markings-reorder"),
                ToggleMode = true,
            };
            _reorderButton.OnToggled += ReorderButtonToggled;
            bottom.AddChild(_reorderButton);
            AddChild(bottom);

            UpdatePointsLabel();
        }

        public Texture SpriteFrame0(MarkingPrototype prototype) => _picker._sprite.Frame0(prototype.Sprites[0]);

        public Texture SpriteFrame0(SpriteSpecifier layer) => _picker._sprite.Frame0(layer);

        public bool IsMarkingApplied(string markingId)
        {
            return _picker._currentMarkings.FindIndexOf(_category, markingId) >= 0;
        }

        public bool IsMarkingColorCustomizable(MarkingPrototype prototype)
        {
            return !prototype.ForcedColoring;
        }

        public Marking? GetMarking(string markingId)
        {
            var index = _picker._currentMarkings.FindIndexOf(_category, markingId);
            if (index < 0)
                return null;

            return _picker._currentMarkings.Markings[_category][index];
        }

        public void OnItemToggled(MarkingItem item, bool pressed)
        {
            if (pressed)
            {
                if (!_picker.TrySelectMarking(item.Prototype, _category))
                {
                    item.ResetSelection();
                    return;
                }
            }
            else
            {
                _picker.TryDeselectMarking(item.Prototype, _category);
            }

            RefreshItems();
            RebuildOrderingList();
        }

        public void RefreshItems()
        {
            foreach (var child in _items.Children)
            {
                if (child is MarkingItem item)
                {
                    item.UpdateSelection();
                }
            }
        }

        private void ReorderButtonToggled(BaseButton.ButtonToggledEventArgs args)
        {
            if (args.Pressed)
            {
                _searchBar.Visible = false;
                _selectionItems.Visible = false;
                _orderingItems.Visible = true;
                RebuildOrderingList();
            }
            else
            {
                _searchBar.Visible = true;
                _selectionItems.Visible = true;
                _orderingItems.Visible = false;
            }
        }

        private void RebuildOrderingList()
        {
            _orderingList.RemoveAllChildren();

            if (!_picker._currentMarkings.TryGetCategory(_category, out var used))
                return;

            foreach (var marking in used)
            {
                if (!_picker._markingManager.TryGetMarking(marking, out var prototype))
                    continue;

                var box = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                    Margin = new Thickness(4),
                    SeparationOverride = 4,
                };

                var preview = new PanelContainer
                {
                    SetSize = new Vector2(64, 64),
                    PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#1B1B1E") },
                };
                preview.AddChild(new LayeredTextureRect
                {
                    Textures = prototype.Sprites.Select(layer => _picker._sprite.Frame0(layer)).ToList(),
                    TextureScale = new Vector2(2, 2),
                });
                box.AddChild(preview);

                box.AddChild(new Label
                {
                    Text = _picker.GetMarkingName(prototype),
                    HorizontalExpand = true,
                    VerticalAlignment = VAlignment.Center,
                });

                var up = new Button { Text = "▲", StyleClasses = { "OpenLeft" } };
                up.OnPressed += _ =>
                {
                    _picker.ShiftMarking(prototype, _category, true);
                    RebuildOrderingList();
                };
                box.AddChild(up);

                var down = new Button { Text = "▼", StyleClasses = { "OpenRight" } };
                down.OnPressed += _ =>
                {
                    _picker.ShiftMarking(prototype, _category, false);
                    RebuildOrderingList();
                };
                box.AddChild(down);

                var remove = new Button { Text = "✕", StyleClasses = { "OpenRight" } };
                remove.OnPressed += _ =>
                {
                    _picker.TryDeselectMarking(prototype, _category);
                    RefreshItems();
                    RebuildOrderingList();
                };
                box.AddChild(remove);

                _orderingList.AddChild(box);
            }
        }

        public void UpdatePointsLabel()
        {
            var points = _picker._currentMarkings.PointsLeft(_category);
            _statusLabel.Text = Loc.GetString("marking-points-remaining", ("points", points));
            _statusLabel.Visible = points > -1;
        }

        public void MarkingColorChange(List<Color> colors, MarkingPrototype prototype)
        {
            _picker.MarkingColorChange(colors, _category, prototype);
        }

        protected override void Resized()
        {
            base.Resized();

            _items.Columns = Math.Max(1, (int)(Width / _columnWidth));
        }
    }

    private sealed class MarkingItem : BoxContainer, ISearchableControl
    {
        private readonly MarkingPrototype _prototype;
        private readonly CategoryTab _tab;

        private readonly Button _selectButton;
        private readonly Button _colorsButton;
        private readonly BoxContainer _colorsContainer;
        private List<ColorSelectorSliders>? _colorSliders;

        public MarkingPrototype Prototype => _prototype;

        public MarkingItem(MarkingPrototype prototype, CategoryTab tab)
        {
            _prototype = prototype;
            _tab = tab;

            Orientation = LayoutOrientation.Vertical;
            HorizontalExpand = true;

            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                SeparationOverride = 4,
                Margin = new Thickness(4),
            };

            var preview = new PanelContainer
            {
                SetSize = new Vector2(64, 64),
                HorizontalAlignment = HAlignment.Left,
                PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#1B1B1E") },
            };
            preview.AddChild(new LayeredTextureRect
            {
                Textures = prototype.Sprites.Select(layer => _tab.SpriteFrame0(layer)).ToList(),
                TextureScale = new Vector2(2, 2),
            });
            row.AddChild(preview);

            _selectButton = new Button
            {
                ToggleMode = true,
                HorizontalExpand = true,
                Text = Loc.GetString($"marking-{prototype.ID}"),
            };
            _selectButton.OnToggled += OnSelectButtonToggled;
            row.AddChild(_selectButton);

            _colorsButton = new Button
            {
                ToggleMode = true,
                Visible = false,
            };
            _colorsButton.AddChild(new TextureRect
            {
                TexturePath = "/Textures/Interface/palette.svg.png",
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                Stretch = TextureRect.StretchMode.Scale,
                SetSize = new Vector2(24, 24),
            });
            _colorsButton.OnToggled += ColorsButtonToggled;
            row.AddChild(_colorsButton);

            AddChild(row);

            _colorsContainer = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                Visible = false,
            };
            AddChild(_colorsContainer);

            UpdateSelection();
        }

        private void OnSelectButtonToggled(BaseButton.ButtonToggledEventArgs args)
        {
            _tab.OnItemToggled(this, args.Pressed);
            UpdateSelection();
        }

        private void ColorsButtonToggled(BaseButton.ButtonToggledEventArgs args)
        {
            _colorsContainer.Visible = args.Pressed;
            UpdateSelection();

            if (!args.Pressed)
                return;

            BuildColorSliders();
        }

        private void BuildColorSliders()
        {
            if (_colorSliders is not null)
                return;

            if (_tab.GetMarking(_prototype.ID) is not { } marking)
                return;

            var stateNames = GetStateNames(_prototype);
            _colorSliders = new();

            for (var i = 0; i < _prototype.Sprites.Count; i++)
            {
                var container = new BoxContainer
                {
                    Orientation = LayoutOrientation.Vertical,
                    HorizontalExpand = true,
                    Margin = new Thickness(8, 2, 0, 2),
                };

                var selector = new ColorSelectorSliders();
                selector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv; // defaults color selector to HSV

                container.AddChild(new Label { Text = stateNames[i] });
                container.AddChild(selector);

                selector.Color = i < marking.MarkingColors.Count ? marking.MarkingColors[i] : Color.White;
                _colorsContainer.AddChild(container);
                _colorSliders.Add(selector);

                var colorIndex = i;
                selector.OnColorChanged += _ =>
                {
                    var colors = new List<Color>();
                    if (_tab.GetMarking(_prototype.ID) is { } currentMarking)
                    {
                        colors = currentMarking.MarkingColors.ToList();
                    }

                    while (colors.Count < _prototype.Sprites.Count)
                    {
                        colors.Add(selector.Color);
                    }

                    while (colors.Count > _prototype.Sprites.Count)
                    {
                        colors.RemoveAt(colors.Count - 1);
                    }

                    colors[colorIndex] = selector.Color;
                    _tab.MarkingColorChange(colors, _prototype);
                };
            }
        }

        private static List<string> GetStateNames(MarkingPrototype marking)
        {
            List<string> result = new();
            foreach (var markingState in marking.Sprites)
            {
                switch (markingState)
                {
                    case SpriteSpecifier.Rsi rsi:
                        result.Add(Loc.GetString($"marking-{marking.ID}-{rsi.RsiState}"));
                        break;
                    case SpriteSpecifier.Texture texture:
                        result.Add(Loc.GetString($"marking-{marking.ID}-{texture.TexturePath.Filename}"));
                        break;
                }
            }

            return result;
        }

        public void ResetSelection()
        {
            _selectButton.Pressed = false;
        }

        public void UpdateSelection()
        {
            var selected = _tab.IsMarkingApplied(_prototype.ID);
            _selectButton.Pressed = selected;
            _colorsButton.Visible = selected && _tab.IsMarkingColorCustomizable(_prototype);

            if (!selected && _colorsButton.Pressed)
            {
                _colorsButton.Pressed = false;
                _colorsContainer.Visible = false;
            }

            if (selected && _colorSliders is { } sliders &&
                _tab.GetMarking(_prototype.ID) is { } marking)
            {
                for (var i = 0; i < _prototype.Sprites.Count && i < sliders.Count; i++)
                {
                    sliders[i].Color = marking.MarkingColors[i];
                }
            }
        }

        public bool CheckMatchesSearch(string query)
        {
            return Loc.GetString($"marking-{_prototype.ID}").Contains(query, StringComparison.OrdinalIgnoreCase);
        }

        public void SetHiddenState(bool state, string query)
        {
            Visible = CheckMatchesSearch(query) ? state : !state;
        }
    }
}