- type: antag
  id: XenomorphsInfestationRoundstart
  name: roles-antag-xenomorph-name
  antagonist: true
  setPreference: true
  category: Team
  icon:
    sprite: _White/Interface/Actions/xenomorph.rsi
    state: egg
  objective: roles-antag-xenomorph-objective
  guides: [ Xenomorphs ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 50h
